@firebaseDbUrl = https://fizu-ace0d.firebaseio.com

GET {{firebaseDbUrl}}/.json
Content-Type: application/json

###
POST {{firebaseDbUrl}}/blogposts.json
Content-Type: application/json

{
 "id": 1,
            "title": "Első bejegyzés",
            "date": "2018-05-09",
            "imageSrc":
                "https://i0.wp.com/www.bluehost.com/blog/wp-content/uploads/2017/12/blog_blog.jpg?resize=350%2C200&ssl=1",
            "lead":
                "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi doloribus, earum, eum aliquam porro repellendus fugiat.",
            "category": "Általános"
        }

###
@apiKey = AIzaSyA7eft0Dfqn3yemE-L4z2OvND4Fv6kVb8I
@signUpUrl = https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser
POST {{signUpUrl}}?key={{apiKey}}
Content-Type: application/json

{
    "email": "zo@z.hu",
    "password": "zozi1977",
    "returnSecureToken": true
}
###
@apiKey = AIzaSyA7eft0Dfqn3yemE-L4z2OvND4Fv6kVb8I
@idToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4OWY3MzQ2YTA5ODVmNDIxZGNkOGQzMGMwYjMwZWViZmFlMTlhMWUifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml6dS1hY2UwZCIsImF1ZCI6ImZpenUtYWNlMGQiLCJhdXRoX3RpbWUiOjE1MzIyMzk5MzcsInVzZXJfaWQiOiJ1UXFaMGMwTkxlVnh0S2t1RkE5UFRvYXk2cWkxIiwic3ViIjoidVFxWjBjME5MZVZ4dEtrdUZBOVBUb2F5NnFpMSIsImlhdCI6MTUzMjIzOTkzNywiZXhwIjoxNTMyMjQzNTM3LCJlbWFpbCI6InpvQHouaHUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiem9Aei5odSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.VBn7qJiMuJdqRy8Cxtv9pOr3W7AgXPUYz4-GZMDS0t4pZR_qqMEdyxfT0OVewP02_I5tOB-i6-BjVfxgKsDjBQAounjHFLz5IUrCO5bz1IgJCHPESLVTfRuqPptfAyLqepPtjNQzHSqYPPPDOrKt4SuOu9Tkyc44WPC57g07Jd_iXWhpcNzGGLnLzsBwrtd4tSCycvcSGdIKufTdABtozu_flUns_KDIBBwygfoJxQpavAL7DMfRhof9av1mjjfSc1EAgYASuXigEPvTyh8ZDEHSUso4JELkeQzK9f2tLZFgGjJsHwegyKVOeVNp2pwd5LgYQ8WH32hfsccmxOeWgw
@refreshToken = AGdpqezU9K2Di2y9fJ9dRwpM6MqVU-p9OjyNv4R4SUoYRAhI043HqXBxbQ34xpvYLT7eG79JOiyZQbjQyhyeqfwP3b8axFeuPhmiU4RyLZwPtVXQChzAeZaTwjTlPcxEU5l-Y9CMJ0ozqnMZxTmkcZMX4UllaSYnH0mRGNJYICgogVZ3JZOs31TQZG4z3-ss7vas1yMClOBo
@signInUrl = https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key
POST {{signInUrl}}?key={{apiKey}}
Content-Type: application/json

{
    "email": "zo@z.hu",
    "password": "zozi1977",
    "returnSecureToken": true
}